
// This file has been generated by the GUI designer. Do not modify.
namespace ACPF
{
	public partial class UniformPlatform
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ACPF.UniformPlatform
			this.Name = "ACPF.UniformPlatform";
			this.Title = global::Mono.Unix.Catalog.GetString ("UniformPlatform");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
